const allowedIds = [
  "Hephzyehi",
  "Ibbello1507",
  "Ulingsmart102008",
  "abelscoliom11",
  "adarikucecilia2",
  "adebayobose235",
  "agujiobisamuel",
  "ajaniisraelojasope11",
  "akinoye7600",
  "anthony87630269",
  "ayibakurokuro",
  "ayomidemilekan23",
  "bilkisumusa888",
  "bokoh5061",
  "chukwukajames131",
  "crys9213",
  "damilolaabolade332",
  "danielisat17",
  "davidoton713",
  "dconfidence322",
  "destinysylvanus74",
  "ebubechiwinner066",
  "ed9583378",
  "edickson774",
  "edickson778",
  "edwardjared723",
  "emmakani234",
  "emmanuelisaacbamgbose",
  "etokwudog",
  "etukubonganthony",
  "ezeisaiah2023",
  "fasootovictor3",
  "feargodthompson",
  "femigodslove069",
  "friedsteak006",
  "geoffreyjootar",
  "godspoweramos01",
  "godswillg057",
  "gomoarukhe",
  "gyess12ee",
  "happybankmoney",
  "hesabasi",
  "icefieldwaripamoweifreedom",
  "idrisamuda06",
  "ifeanyichukwuoguejiofor",
  "imajerry1819",
  "jibarnabas17",
  "jnrfred74",
  "josephjoeboy445",
  "kehindeige527",
  "mayrhejaneluv",
  "mujaheedpresdor001",
  "muslimatkehinde05",
  "obunsodaniel",
  "ojetunbiseun",
  "olamilekanjoseph601",
  "oluwatofunmienochoke",
  "opalekesoromdayo",
  "osuolalemubarak7",
  "owolabidamilare377",
  "paschalifechukwu2006",
  "popoolaisrael73",
  "raetharolin",
  "safiyaibrahimbahago",
  "sermborleeh",
  "sesughdaniel433",
  "sikinsam24",
  "simonejembi783",
  "sunsuwaamagai2020",
  "tmosco4real",
  "twostorage554",
  "uduakabasieniang",
  "unwanaidiong2008",
  "usohisrael2",
  "utomobongpatrick16",
  "victorumoren113",
  "whizzyboss67",
  "winnerfelix094"
];

const currentUserId = localStorage.getItem("Id");
const storedStatus = localStorage.getItem("activateStatus");

if (currentUserId && allowedIds.includes(currentUserId) && storedStatus !== "present") {
  localStorage.setItem("activateStatus", "present");
  console.log(`activateStatus set to 'present' for allowed user: ${currentUserId}`);
} else if (!allowedIds.includes(currentUserId)) {
  console.log(`User ${currentUserId} is NOT allowed. activateStatus not set.`);
} else {
  console.log(`activateStatus already set for this user: ${currentUserId}`);
}